// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBqqNvjeyKH3BRlk-kl671rqf-amPL9lw',
    appId: '1:139160455468:android:a9536f91a2bb4787640489',
    messagingSenderId: '139160455468',
    projectId: 'iprasad-notes-flutter-firebase',
    storageBucket: 'iprasad-notes-flutter-firebase.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRnD8t_G1tfuN756FNf8xNJvG3LnV9pbw',
    appId: '1:139160455468:ios:1fd8fb9baa1ca04b640489',
    messagingSenderId: '139160455468',
    projectId: 'iprasad-notes-flutter-firebase',
    storageBucket: 'iprasad-notes-flutter-firebase.firebasestorage.app',
    iosBundleId: 'com.iprasad.notes',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgOzji3-LmueZHe7o4qbb8s13kJi6UIB0',
    appId: '1:139160455468:web:885a416c748ec0be640489',
    messagingSenderId: '139160455468',
    projectId: 'iprasad-notes-flutter-firebase',
    authDomain: 'iprasad-notes-flutter-firebase.firebaseapp.com',
    storageBucket: 'iprasad-notes-flutter-firebase.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRnD8t_G1tfuN756FNf8xNJvG3LnV9pbw',
    appId: '1:139160455468:ios:1fd8fb9baa1ca04b640489',
    messagingSenderId: '139160455468',
    projectId: 'iprasad-notes-flutter-firebase',
    storageBucket: 'iprasad-notes-flutter-firebase.firebasestorage.app',
    iosBundleId: 'com.iprasad.notes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDgOzji3-LmueZHe7o4qbb8s13kJi6UIB0',
    appId: '1:139160455468:web:3cf0747a14dd10a6640489',
    messagingSenderId: '139160455468',
    projectId: 'iprasad-notes-flutter-firebase',
    authDomain: 'iprasad-notes-flutter-firebase.firebaseapp.com',
    storageBucket: 'iprasad-notes-flutter-firebase.firebasestorage.app',
  );

}